# Generated by Django 3.2.2 on 2021-05-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erkinSavdoApp', '0002_alter_home_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='rentOrSent',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Rent m', 'Rent m'), ('Rent w', 'Rent w'), ('Rent d', 'Rent d')], default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='typeOfHouse',
            field=models.CharField(choices=[('Kvartira', 'Kvartira'), ('Hovli', 'Hovli'), ('Ofis', 'Ofis'), ("Do'kon", "Do'kon")], default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='profilePicture',
            field=models.ImageField(default='default-user.png', upload_to='profilePic'),
        ),
        migrations.CreateModel(
            name='TopHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('dueDate', models.DateTimeField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erkinSavdoApp.home')),
            ],
        ),
    ]
