# Generated by Django 3.2.2 on 2021-06-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erkinSavdoApp', '0004_auto_20210606_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='lengthOfRooms',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
