# Generated by Django 3.2.2 on 2021-06-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erkinSavdoApp', '0006_auto_20210609_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
