# Generated by Django 3.2.2 on 2021-06-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erkinSavdoApp', '0008_auto_20210609_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='home',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='home',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='home',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='home',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='home',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='home',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='home',
            name='area',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='home',
            name='priceType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erkinSavdoApp.pricetype'),
        ),
    ]
