# Generated by Django 3.2.2 on 2021-06-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erkinSavdoApp', '0009_auto_20210609_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image8',
        ),
    ]
