# Generated by Django 3.2.2 on 2021-06-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erkinSavdoApp', '0010_auto_20210609_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'UZ'), ('ru', 'RU'), ('en', 'EN')], max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='home',
            old_name='rentOrSent',
            new_name='rentOrSale',
        ),
        migrations.RemoveField(
            model_name='home',
            name='region',
        ),
        migrations.AddField(
            model_name='district',
            name='language',
            field=models.CharField(choices=[('uz', 'UZ'), ('ru', 'RU'), ('en', 'EN')], default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='language',
            field=models.CharField(choices=[('uz', 'UZ'), ('ru', 'RU'), ('en', 'EN')], default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erkinSavdoApp.district'),
        ),
        migrations.AlterField(
            model_name='home',
            name='typeOfHouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erkinSavdoApp.hometype'),
        ),
    ]
